version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      # --- TESTING ---
      # Run the docker test target that produces the report files
      - docker build --rm=false -t codebuild-app:latest .
      - id=`docker images --filter "label=test_stage=true"  -q`
      - docker tag $id mychep-core-test:latest
      - docker cp mychep-core-test:latest:portfolio-plus-core/target/failsafe-reports test-reports
      # Create a container from the image (without starting)
      # - docker create --name codebuild-app-test codebuild-app:latest
      # Copy the relevant report files & clean-up
      # - docker cp codebuild-app-test:/app/target/surefire-reports .
      # - docker rm codebuild-app-test

      # --- BUILDING ---
      # continue with regular build
  post_build:
    commands:
      - echo Build completed on `date`
reports:
  SurefireReports:
    files:
      - '**/*'
    base-directory: 'test-reports'