version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - docker build --target test -t codebuild-test:latest .
  post_build:
    commands:
      - echo Build completed on `date`
